### ISSUE TITLE
Installation complexity rolls over

### ISSUE THREAD

**Issue by nikitinsm** [veegee/guv#19]
I spent about 2 hours trying to make libuv 1.x under Ubuntu and gave up. I think that end-user of a such module does not even know that C/C++ appear in this world (joking of course) but they really could lost in such routines like configuring and making C/C++ projects. But for me GUV looks like very interesting and the only one alternative of terrible and slow supporting Gevent. So is it possible to make installation more user friendly. For example to bundle together all requirements. Or prepare docker image for instance (with separate environments of cpython and pypy). It would help people to envolve project faster.

**Comment by veegee** [comment]
Installing libuv is *very* straightforward:

1. `sudo aptitude install -y build-essential automake libtool`
2. `sh autogen.sh`
3. `./configure --prefix=/usr/local`
4. `make`
5. `make install`
6. `sudo ldconfig`

Then guv will work. Let me know how it goes.

**Comment by nikitinsm** [comment]
Nope it does not work 

```
sh autogen.sh
: not found 2: autogen.sh: 
: not found 16: autogen.sh: 
autogen.sh: 17: cd: can't cd to .
: not found 18: autogen.sh: 
autogen.sh: 47: autogen.sh: Syntax error: end of file unexpected (expecting "then")
```

**Comment by veegee** [comment]
Wow I have no idea what's going on there haha, I can't replicate that. But this is definitely something you should post on the libuv issue tracker. In the meantime, I'll keep this issue open here and see if I can bundle libuv with guv.

**Comment by nikitinsm** [comment]
I'll try to setup on clean os later or tomorrow.

**Comment by nikitinsm** [comment]
Never the less for example gevent bundles all sources inside it self.

**Comment by veegee** [comment]
Since the problem that you're having has to do with `libuv`, I'll close this issue for now. I'll work towards making it easier to install, but with Ubuntu 15.04 around the corner, installing libuv should be much easier.
