### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by noodlebreak** [veegee/guv#21]
I install libuv, after downloading it to `/tmp/libuv/`.
I installed it, using the instructions in their readme.

Then I cloned guv, and on running installation, I get this:

```
pyuv_cffi/__pycache__/_cffi__x4295e1d1xf9520033.c:190:16: fatal error: uv.h: No such file or directory
 #include <uv.h>
                ^
compilation terminated.
CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Am I missing something here? First of all, libuv has python files written in python 2.x
So I had to run its installer in my global python environment, with the python 2.x installation.

Then I entered my virtualenv, and ran the guv's installation script. And above error is what I got.

I even tried to install `guv` after deactivating my virtualenv, hoping maybe it's a virtualenv thing. Still the same error.

But please note that, I need to install it in a python3 virtualenv.

**Comment by veegee** [comment]
This doesn't look like a serious issue. All it's saying is that it can't find the libuv header, meaning that libuv wasn't installed correctly. You should make sure that `uv.h` is in `/usr/include/` and then run `sudo ldconfig` after manually installing libuv.

**Comment by veegee** [comment]
Since this looks like an issue related to the correct installation of libuv, I'll close it unless you report otherwise.
