### ISSUE TITLE
Why use guv instead gevent?

### ISSUE THREAD

**Issue by jaddison** [veegee/guv#30]
Now that gevent supports Python 3, is there a reason for guv's existence? What major differences/advantages does guv have over gevent at this point?

Just looking for data points to make decisions.

**Comment by veegee** [comment]
At this point, you should definitely use gevent in production since it's widely tested. Guv is experimental. It's faster than gevent, uses libuv and is much cleaner and more portable in design, works with pypy3, but there are more bugs and it doesn't get nearly as much attention and work put into it as gevent.

**Comment by jaddison** [comment]
Do you know if there are there plans for gevent to draw on some of the lessons learned in the project, pull some code in, switch to `libuv`, etc? Has it been suggested at all? I think it would be fantastic for gevent to gain some speed, if applicable - it's already fast, but faster is better than fast, right? :)

**Comment by veegee** [comment]
This project can get ahead of gevent if more engineers put time into it. As much as I'd love to, I simply don't have the time these days, which is really unfortunate, so there is no one working on it at the moment.

Gevent is a very old codebase and as such has accumulated its share of technical debt. They have to try to keep a stable API and compatibility with Python 2, so it's not very easy for them to be changing around a lot of stuff at this point. There is actually a libuv core for gevent [here](https://github.com/saghul/uvent) if you're interested. You could try creating a benchmark and comparing with the default event loop.

To be honest, I've mostly moved on from Python to Scala and Go where I don't have to worry about doing things like heavily monkey patching the standard library and changing core behaviour just to get some performance. If I try very hard, CPython with Guv will give me 10k req/sec max. Go and Scala will easily give me 90k req/sec on the same computer, and I don't even have to do anything crazy like this.

**Comment by jaddison** [comment]
Thanks for the feedback.
