### ISSUE TITLE
Thread does not support setDaemon()

### ISSUE THREAD

**Issue by jasonab** [veegee/guv#34]
I'm using a library that's calling setDaemon() on the thread class, but that throws an error when green/Thread is patched in, because that method is missing.

**Comment by veegee** [comment]
Do you think you can add that method? I would love some help with this library since I'm lacking time these days.

**Comment by jasonab** [comment]
Sure, no problem. Just wanted to make sure I wasn't missing anything.

**Comment by veegee** [comment]
Your commit has been merged, thanks! Please feel free to contribute anywhere you see fit. I would like to work on this library more, but I definitely can't do it alone with the time I have these days.

**Comment by jasonab** [comment]
Thanks, I've been looking for a better socket library for Python for a while, but most of the fast ones don't support Python 3. Unfortunately, I'm not a C sockets expert, but if I run across anything, I'll do what I can.
